name: Build
on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - main
      - net80incremental
jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: Statiq.Web
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    env:
      # https://github.com/NuGet/Home/issues/11548
      # https://twitter.com/xoofx/status/1488617114940452872?s=20&t=BKSN4j9rP6fOyg8l7aW0eg
      NUGET_CERT_REVOCATION_MODE: offline
    steps:
      - name: Get Source
        uses: actions/checkout@v4
        with:
          path: Statiq.Web
          submodules: recursive
      - name: Checkout Statiq.Framework
        uses: actions/checkout@v4
        with:
          repository: flcdrg/Statiq.Framework # Using my fork for now
          path: Statiq.Framework
          submodules: recursive
          ref: net80incremental
      - name: Install .NET Core SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            8.x
      - name: Build and Test
        run: dotnet test --logger "trx;LogFileName=test-results.trx"
      - name: Upload Test Results
        uses: actions/upload-artifact@v3
        if: success() || failure()
        with:
          name: test-results-${{ matrix.os }}
          path: '**/test-results.trx'